export const PROJECT_LIST_REQUEST = "PROJECT_LIST_REQUEST";
export const PROJECT_LIST_SUCCESS = "PROJECT_LIST_SUCCESS";
export const PROJECT_LIST_FAIL = "PROJECT_LIST_FAIL";

export const PROJECT_CREATE_REQUEST = "PROJECT_CREATE_REQUEST";
export const PROJECT_CREATE_SUCCESS = "PROJECT_CREATE_SUCCESS";
export const PROJECT_CREATE_FAIL = "PROJECT_CREATE_FAIL";
export const PROJECT_CREATE_RESET = "PROJECT_CREATE_RESET";

export const PROJECT_UPDATE_REQUEST = "PROJECT_UPDATE_REQUEST";
export const PROJECT_UPDATE_SUCCESS = "PROJECT_UPDATE_SUCCESS";
export const PROJECT_UPDATE_FAIL = "PROJECT_UPDATE_FAIL";
export const PROJECT_UPDATE_RESET = "PROJECT_UPDATE_RESET";

export const PROJECT_DELETE_REQUEST = "PROJECT_DELETE_REQUEST";
export const PROJECT_DELETE_SUCCESS = "PROJECT_DELETE_SUCCESS";
export const PROJECT_DELETE_FAIL = "PROJECT_DELETE_FAIL";
export const PROJECT_DELETE_RESET = "PROJECT_DELETE_RESET";

export const TASK_TOGGLE_REQUEST = "TASK_TOGGLE_REQUEST";
export const TASK_TOGGLE_SUCCESS = "TASK_TOGGLE_SUCCESS";
export const TASK_TOGGLE_FAIL = "TASK_TOGGLE_FAIL";
export const TASK_TOGGLE_RESET = "TASK_TOGGLE_RESET";

export const TASK_ADD_REQUEST = "TASK_ADD_REQUEST";
export const TASK_ADD_SUCCESS = "TASK_ADD_SUCCESS";
export const TASK_ADD_FAIL = "TASK_ADD_FAIL";
export const TASK_ADD_RESET = "TASK_ADD_RESET";

export const TASK_DELETE_REQUEST = "TASK_DELETE_REQUEST";
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
export const TASK_DELETE_FAIL = "TASK_DELETE_FAIL";
export const TASK_DELETE_RESET = "TASK_DELETE_RESET";
